name: Cleanup Merged PR

on:
  pull_request:
    types:
      - closed
    branches:
      - main

  workflow_dispatch:

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}
  NODE_ENV: dev
  AWS_REGION: us-east-2
  APP_NAME: nextjs-demo

jobs:
  cleanup-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Destroy CDK Stack
        run: |
          aws cloudformation delete-stack --stack-name "microapps-app-${APP_NAME}-${NODE_ENV}-pr-${PR_NUMBER}"
          aws cloudformation wait stack-delete-complete --no-paginate --output text --stack-name "microapps-app-${APP_NAME}-${NODE_ENV}-pr-${PR_NUMBER}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
